---
title: "Final Project"
author: "She Zhang"
date: "August 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Set seeds
```{r}
set.seed(3108)
lambda <- 0.2
```

## Simulations
```{r}
# Sample size is 40, there are 1000 simulations
n <- 40
B <- 1000

# Get 1000 simulations, each simulation has a size of 40
mns = NULL
for (i in 1 : B) mns = c(mns, rexp(n, rate=lambda))
sims = matrix(mns, nrow=B, ncol=n)
```

## Sample Mean versus Theoretical Mean

```{r}
# Sample Mean
samplemean <- mean(rowMeans(sims))
samplemean

# Theoretical Mean
themean <- 1/lambda
themean

# Plot sample mean and theoretical mean
hist(rowMeans(sims), xlab = "Sample Mean", breaks = n, main="Histogram of sample mean")
abline(v = samplemean, col = "green")
abline(v = themean, col = "red")

# Sample mean is very close to the theoretical mean.
```

## Sample Variance versus Theoretical Variance

```{r}
# Sample variance
var(rowMeans(sims))

# Theoretical variance
1 / ((lambda^2) * n)

# Again, sample variance is very close to theoretical variance.
```

## Distribution
```{r}
qqnorm(rowMeans(sims))
qqline(rowMeans(sims), col = 2)

# The distribution of 40 averages of exponential distributions is very close to
# a normal distribution.
```
